version: '3'
services:
  mongodb:
    # image -> sempre de repositorio externo
    image: mongo:3.5
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api-heroes:
    # informamos o build, que é a pasta onde o dockerfile está
    build: .
    # variáveis de ambiente
    environment:
      MONGO_URL: mongodb
      PORT: 4000
    ports:
      - 4000:4000
    # definimos permissão de acesso ao mongo
    links:
      - mongodb
    # definimos que o mongo tem que subir primeiro  
    depends_on:
      - mongodb
